import { z } from 'zod';
import type { Database } from './database.types';

/**
 * Row, insert and enum shapes taken from the database itself.
 *
 * Before this existed, every component declared its own copy of the table it read — an
 * interface written next to the query and maintained by remembering to. That is how DEF-023
 * happened: the corrective-action form inserted a `photo_url` column no schema ever had, and
 * nothing could compare the two. It is also how six components ended up disagreeing with the
 * schema about nullability and about which values a status column may hold.
 *
 * `database.types.ts` is generated by `npm run gen:types` from the applied migrations. These
 * aliases are the only thing application code should import.
 */

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type Inserts<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

export type Enums<T extends keyof Database['public']['Enums']> =
  Database['public']['Enums'][T];

export type Profile = Tables<'profiles'>;
export type Organization = Tables<'organizations'>;
export type Equipment = Tables<'equipment'>;
export type Inspection = Tables<'inspections'>;
export type InspectionInsert = Inserts<'inspections'>;
export type CorrectiveAction = Tables<'corrective_actions'>;
export type Schedule = Tables<'schedules'>;
export type Notification = Tables<'notifications'>;

export type UserRole = Enums<'user_role'>;
export type InspectionStatus = Enums<'inspection_status'>;
export type CorrectiveStatus = Enums<'corrective_status'>;
export type CorrectiveSeverity = Enums<'corrective_severity'>;
export type ScheduleFrequency = Enums<'schedule_frequency'>;

/**
 * The checklist stored on an inspection.
 *
 * `checklist_data` is `jsonb`, so the generated type is `Json` — genuinely unknown-shaped at
 * the boundary, because Postgres does not constrain what is inside a jsonb column. Components
 * used to index straight into it as an array, which is an assumption dressed as a type: a row
 * written by an older client, a partial sync, or a hand-edited record would crash the render.
 *
 * Parsing at the boundary is the honest version. A malformed checklist yields an empty list
 * and the record still renders, rather than taking the page down.
 */
export const checklistEntrySchema = z.object({
  id: z.string(),
  question: z.string(),
  status: z.string(),
});

export type ChecklistEntry = z.infer<typeof checklistEntrySchema>;

export function asChecklist(value: unknown): ChecklistEntry[] {
  const parsed = z.array(checklistEntrySchema).safeParse(value);
  return parsed.success ? parsed.data : [];
}
