'use client';

// EU AI Act Article 50(1) disclosure.
//
// Deliberately NOT dismissible and NOT animated in. Two reasons, both learned here:
// a disclosure the user can close is a disclosure that was not made, and DEF-012 established
// that anything gated behind an entrance animation may never render at all. Compliance copy
// renders from HTML on first paint or it is not compliance copy.
//
// All wording comes from `src/content/ai-disclosure.json` via the ai-act module — legal text
// has one owner and it is not a TSX file.

import { Sparkles, AlertTriangle } from 'lucide-react';
import { aiDisclosure, type AiProvenance } from '@/lib/compliance/ai-act';

/** Small inline marker for a single AI-derived field. */
export function AiBadge({ className = '' }: { className?: string }) {
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-md bg-accent/15 px-1.5 py-0.5 text-[10px] font-medium uppercase tracking-wide text-accent ${className}`}
      title={aiDisclosure.badge.tooltip}
    >
      <Sparkles className="h-3 w-3" aria-hidden="true" />
      {aiDisclosure.badge.label}
    </span>
  );
}

/**
 * Full disclosure panel shown whenever AI has produced content the user is about to rely on.
 *
 * `provenance` is rendered when present so the user can see *which* system produced the
 * result, not merely that "AI" did — Art. 50 transparency is about a specific system.
 */
export function AiDisclosurePanel({ provenance }: { provenance?: AiProvenance | null }) {
  return (
    <section
      // `role="note"` rather than `alert`: this is standing context, not an interruption,
      // and an alert role would be announced over the technician's current task.
      role="note"
      aria-label={aiDisclosure.inline.heading}
      className="rounded-lg border border-accent/40 bg-accent/5 p-4"
    >
      <div className="flex items-start gap-3">
        <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-accent" aria-hidden="true" />
        <div className="space-y-2">
          <h3 className="text-sm font-semibold text-foreground">
            {aiDisclosure.inline.heading}
          </h3>
          <p className="text-xs leading-relaxed text-muted-foreground">
            {aiDisclosure.inline.body}
          </p>
          <p className="text-xs font-medium leading-relaxed text-foreground">
            {aiDisclosure.inline.action}
          </p>
          {provenance && (
            <p className="pt-1 text-[10px] text-muted-foreground">
              Generated by{' '}
              <span className="font-mono">{provenance.provider}</span>
              {' / '}
              <span className="font-mono">{provenance.model}</span>
              {' · '}
              <time dateTime={provenance.disclosedAt}>
                {new Date(provenance.disclosedAt).toLocaleString()}
              </time>
            </p>
          )}
        </div>
      </div>
    </section>
  );
}
