import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';

// Define styles for the PDF
const styles = StyleSheet.create({
  page: { padding: 30, fontFamily: 'Helvetica' },
  header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20, borderBottom: 1, paddingBottom: 10, borderColor: '#ccc' },
  title: { fontSize: 24, fontWeight: 'bold', color: '#111' },
  subtitle: { fontSize: 10, color: '#666', marginTop: 5 },
  section: { margin: 10, padding: 10 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 },
  label: { fontSize: 10, color: '#666', width: 100 },
  value: { fontSize: 10, fontWeight: 'bold', width: 200 },
  
  // Table Styles
  tableHeader: { flexDirection: 'row', backgroundColor: '#f0f0f0', padding: 5, marginTop: 10 },
  tableRow: { flexDirection: 'row', borderBottom: 1, borderColor: '#eee', padding: 5 },
  colQuestion: { width: '70%', fontSize: 10 },
  colStatus: { width: '30%', fontSize: 10, fontWeight: 'bold' },
  
  // Status Colors
  pass: { color: 'green' },
  fail: { color: 'red' },
  
  // Photo
  imageSection: { marginTop: 20, height: 200, alignItems: 'center' },
  image: { width: 300, height: 200, objectFit: 'contain', borderRadius: 5 },
  
  footer: { position: 'absolute', bottom: 30, left: 30, right: 30, textAlign: 'center', fontSize: 8, color: '#aaa' }
});

// Define the data shape
interface InspectionData {
  id: number;
  equipment_name: string;
  inspector_name: string;
  created_at: string;
  status: string;
  photo_url: string | null;
  checklist_data: any[]; // The JSON array of questions
}

export const InspectionReportPDF = ({ data }: { data: InspectionData }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      
      {/* Header */}
      <View style={styles.header}>
        <View>
          <Text style={styles.title}>Safety Report</Text>
          <Text style={styles.subtitle}>EquipCert AI Compliance</Text>
        </View>
        <View>
           <Text style={{ fontSize: 10 }}>ID: #{data.id}</Text>
           <Text style={{ fontSize: 10 }}>{new Date(data.created_at).toLocaleDateString()}</Text>
        </View>
      </View>

      {/* Info Section */}
      <View style={styles.section}>
        <View style={styles.row}>
          <Text style={styles.label}>Equipment:</Text>
          <Text style={styles.value}>{data.equipment_name}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Inspector:</Text>
          <Text style={styles.value}>{data.inspector_name}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Overall Status:</Text>
          <Text style={[styles.value, data.status === 'Safe' ? styles.pass : styles.fail]}>
            {data.status.toUpperCase()}
          </Text>
        </View>
      </View>

      {/* Checklist Table */}
      <View style={styles.section}>
        <Text style={{ fontSize: 14, fontWeight: 'bold', marginBottom: 5 }}>Checklist Results</Text>
        
        {/* Table Head */}
        <View style={styles.tableHeader}>
          <Text style={styles.colQuestion}>Item</Text>
          <Text style={styles.colStatus}>Status</Text>
        </View>

        {/* Table Body */}
        {data.checklist_data && Array.isArray(data.checklist_data) ? (
          data.checklist_data.map((item: any, i: number) => (
            <View key={i} style={styles.tableRow}>
              <Text style={styles.colQuestion}>{item.question}</Text>
              <Text style={[styles.colStatus, item.status === 'pass' ? styles.pass : styles.fail]}>
                {item.status.toUpperCase()}
              </Text>
            </View>
          ))
        ) : (
          <Text style={{ fontSize: 10, fontStyle: 'italic', padding: 5 }}>No checklist data available</Text>
        )}
      </View>

      {/* Evidence Photo */}
      {data.photo_url && (
        <View style={styles.imageSection}>
          <Text style={{ fontSize: 12, marginBottom: 5 }}>Visual Evidence:</Text>
          {/* Note: React-PDF requires 'Access-Control-Allow-Origin' on the image source */}
          <Image src={data.photo_url} style={styles.image} />
        </View>
      )}

      {/* Footer */}
      <Text style={styles.footer}>
        Generated by EquipCert AI • Authorized by {data.inspector_name} • Securely Stored in Supabase
      </Text>

    </Page>
  </Document>
);